# Generated by Django 2.1.1 on 2018-10-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('monitered_items', models.CharField(max_length=200)),
                ('price_restrictions', models.CharField(max_length=200)),
                ('wear_restrictions', models.CharField(max_length=200)),
                ('rare_restrictions', models.CharField(max_length=200)),
            ],
        ),
    ]
