# Generated by Django 2.1.1 on 2018-10-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsgoApi',
            fields=[
                ('buff_api', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('igxe_api', models.CharField(max_length=20)),
                ('buff_name', models.CharField(max_length=100)),
                ('igxe_name', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('monitored_items', models.CharField(max_length=200)),
                ('price_restrictions', models.CharField(max_length=200)),
                ('wear_restrictions', models.CharField(max_length=200)),
                ('rare_restrictions', models.CharField(max_length=200)),
            ],
        ),
    ]
