# Generated by Django 2.1.1 on 2018-10-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0002_auto_20181009_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='csgoapi',
            name='catagory',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
