# Generated by Django 2.1.1 on 2018-10-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0003_csgoapi_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
