# Generated by Django 2.1.1 on 2018-10-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0005_declare'),
    ]

    operations = [
        migrations.AddField(
            model_name='declare',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
