# Generated by Django 2.1.1 on 2018-10-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0006_declare_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='monitored_items',
        ),
        migrations.AddField(
            model_name='user',
            name='monitored_buff_apis',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='monitored_igxe_apis',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
