# Generated by Django 2.1.1 on 2018-10-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('go', '0007_auto_20181013_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='monitored_buff_apis',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
